version: "3"
services:
  api:
    env_file: ./backend/.env
    volumes:
      - ./backend/ormconfig.docker.json:/home/api/ormconfig.json

  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bycoders

  pgadmin-4:
    environment:
      PGADMIN_DEFAULT_EMAIL: "dev@bycoders.com.br"
      PGADMIN_DEFAULT_PASSWORD: "dev@1234"
